name: 'Setup Yarn'
description: 'Sets up an Yarn development environment.'

branding:
  icon: node
  color: blue

inputs:
  node-version:
    description: 'The version of node to use.'
    default: 'v23.8.0'

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'
    - name: Install Yarn
      run: |
        npm install yarn
      shell: bash
    - name: Install dependencies
      run: |
        yarn install
        yarn build
      shell: bash
    - name: Log Installed Tools
      run: |
        echo "node: $(node --version)"
        echo "yarn: $(yarn --version)"
      shell: bash