[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
kermes_staking = "3aWDZ2X82E8mx6ACPmKhmvsZUwXftQtQF9u9vTjnJ6FV"
kermes_vault_share = "9QZeymvqEZukDWVKTMv5S2BoL7bHKPUpnVv3cmmHE8J1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn vitest run --test-timeout 1000000 --no-file-parallelism --globals"
