name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: "2.1.14"
  RUST_TOOLCHAIN: stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Solana BPF tools
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          export PATH="/root/.local/share/solana/install/active_release/bin:$PATH"
          solana-install init

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install latest
          avm use latest

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          export PATH="/root/.local/share/solana/install/active_release/bin:$PATH"
          anchor build 