name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  clippy:
    runs-on: ubuntu-latest
    container: rust:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/node
      - name: Build packages
        run: yarn build
      - name: Lint
        run: yarn lint