name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  clippy:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Yarn
        uses: ./.github/actions/yarn
      - name: Lint
        run: yarn lint