name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Anchor
        uses: ./.github/actions/anchor
      - name: Install dependencies
        run: yarn install
      - name: Build packages
        run: yarn build